# -----------------------------------------------------------------------------
# Site Info
# -----------------------------------------------------------------------------

title: Sreya Sarkar
first_name: Sreya
last_name: Sarkar
#description: >
#  Statistician working on high-dimensional repeated measures data, multimodal inference, and Bayesian computation.
#contact_note: >
#  Feel free to reach out via email for academic discussions or collaborations.

author:
  name: Sreya Sarkar
  email: sreya-sarkar@uiowa.edu
  github: SreyaSarkar21
  linkedin: sreya-sarkar-6448231a0
  # scholar: your-google-scholar-id
  cv: /assets/files/cv.pdf
contact_note: >
  Alternate email: sreyasarkar1998@gmail.com

lang: en
icon: 📊

url: "https://sreyasarkar21.github.io"
baseurl: ""

# -----------------------------------------------------------------------------
# Features
# -----------------------------------------------------------------------------

enable_darkmode: true
# enable_math: true
# enable_masonry: true
# enable_project_categories: true
enable_navbar_social: true

navbar_fixed: true
footer_fixed: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll/scholar
  - jemoji
  - jekyll-toc
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-terser
  - jekyll-imagemagick

# -----------------------------------------------------------------------------
# Scholar Settings (for Publications later)
# -----------------------------------------------------------------------------

#scholar:
#  last_name: [Sarkar]
#  first_name: [Sreya]
#  style: apa
#  locale: en
#  source: /_bibliography/
#  bibliography: papers.bib
#  bibliography_template: bib
#  group_by: year
#  group_order: descending
#  max_author_limit: 

# -----------------------------------------------------------------------------
# Image and Link Handling
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true
  widths: [480, 800, 1400]
  input_directories: [assets/img/]
  input_formats: [".jpg", ".jpeg", ".png", ".tiff", ".gif"]
  output_formats:
    webp: "-quality 85"

lazy_loading_images: true

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
